# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Disable 4G Control Plane
omec-control-plane:
  enable4G: false

# Disable 5G RAN Simulator
5g-ran-sim:
  enable: false

# Override values for 5g-control-plane Helm Chart
# https://github.com/omec-project/sdcore-helm-charts/blob/main/5g-control-plane/values.yaml
5g-control-plane:
  enable5G: true
  images:
    repository: ""    # defaults to Docker Hub
    #tags:
    #  amf: <amf image tag>
    # refer to above Helm Chart to add other NF images

  kafka:
    deploy: true

  mongodb:
    usePassword: false
    persistence:
      enabled: false
    architecture: replicaset
    replicaCount: 2
  resources:
    enabled: false

  config:
    # logger:
    #   # network function
    #   AMF:
    #     debugLevel: trace
    #     ReportCaller: false
    #   SMF:
    #     debugLevel: trace
    #     ReportCaller: false

    mongodb:
      name: free5gc
      url: mongodb://mongodb-arbiter-headless # Enable if cluster deployment required
      authKeysDbName: authentication
      authUrl: mongodb://mongodb-arbiter-headless

    managedByConfigPod:
      enabled: true
      syncUrl: http://sdcore-adapter-v2-1.aether-roc.svc:8080/synchronize

    sctplb:
      deploy: true # If enabled then deploy sctp pod
      ngapp:
        externalIp: {{ core.amf.ip }}
        port: 38412

    upfadapter:
      deploy: false # If enabled then deploy upf adapter pod

    metricfunc:
      deploy: true

    # Change AMF config here if rquired
    # Most of the AMF config comes from Slice APIs but some of the config is
    # directly provided through Helm Charts
    amf:
      cfgFiles:
        amfcfg.conf:
          configuration:
            enableDBStore: true # Store AMF subscribers in the datastore

    # SMF config override. Refer to Helm Charts values for more options
    smf:
      cfgFiles:
        smfcfg.conf:
          configuration:
            enableDBStore: true  # Store SMF subscribers in the datastore

    #pcf:
    #  cfgFiles:
    #    pcfcfg.conf:
    #      configuration:

    nrf:
      cfgFiles:
        nrfcfg.conf:
          configuration:
            mongoDBStreamEnable: false    # enable/disable MongoDB stream in NRF
            nfProfileExpiryEnable: true   # If enabled, remove NF profile if no keepalive received
            nfKeepAliveTime: 60           # default timeout for NF profiles


# Override values for omec-sub-provision (subscriber) Helm Chart
# https://github.com/omec-project/sdcore-helm-charts/blob/main/omec-sub-provision/values.yaml
# ***Note: Most of these values can (and should) be set via ROC API***
omec-sub-provision:
  enable: true
  images:
    repository: ""    # defaults to Docker Hub
    #tags:
    #  simapp: #add simapp override image

  config:
    simapp:
      cfgFiles:
        simapp.yaml:
          configuration:
            provision-network-slice: {{ core.standalone | string }} # if enabled, Device Groups & Slices configure by simapp
            sub-provision-endpt:
              addr: webui.omec.svc.cluster.local  # subscriber configuation endpoint.
            # sub-proxy-endpt: # used if subscriber proxy is enabled in the ROC.
            #   addr: subscriber-proxy.aether-roc.svc.cluster.local
            #   port: 5000

            # Configure Subscriber IMSIs and their security details.
            # You can have any number of subscriber ranges
            # This block is always necessary to establish range(s) of valid IMSIs
            subscribers:
            - ueId-start: "001010123456864"
              ueId-end: "001010123456868"
              plmnId: "00101"
              opc: "00000000000000000000000000000000"
              op: ""
              key: "ffffffffffffffffffffffffffffffff"
              sequenceNumber: "16f3b3f70fc2"

            # Configure Device Groups (ignored if provision-network-slice is disabled)
            device-groups:
            - name:  "5g-user-group1"
              imsis:
                - "001010123456864"
                - "001010123456865"
              ip-domain-name: "pool1"
              ip-domain-expanded:
                dnn: internet
                dns-primary: "8.8.8.8"        # Value is sent to UE
                mtu: 1460                     # Value is sent to UE when PDU Session Established
                ue-ip-pool: "172.250.1.0/16"  # IP address pool for subscribers
                ue-dnn-qos:
                  dnn-mbr-downlink: 1000      # UE level downlink QoS (Maximum bit rate per UE)
                  dnn-mbr-uplink:   1000      # UE level uplink QoS (Maximum bit rate per UE)
                  bitrate-unit: Mbps          # Unit for above QoS rates
                  traffic-class:              # Default bearer QCI/ARP (not used in 5G)
                    name: "platinum"
                    qci: 9
                    arp: 6
                    pdb: 300
                    pelr: 6
              site-info: "enterprise"
            # UPF allocates IP address if there is only 1 device-group
            # SMF allocates IP address if there is >1 device-group

            # Configure Network Slices (ignored if provision-network-slice is disabled)
            network-slices:
            - name: "default"      # can be any unique slice name
              slice-id:            # must match with slice configured in gNB, UE
                sd: "010203"
                sst: 1
              site-device-group:
              - "5g-user-group1"   # All UEs in this device-group are assigned to this slice
              # Applicaiton filters control what each user can access.
              # Default, allow access to all applications
              application-filtering-rules:
              - rule-name: "ALLOW-ALL"
                priority: 250
                action: "permit"
                endpoint: "0.0.0.0/0"
              site-info:
                # Provide gNBs and UPF details and also PLMN for the site
                gNodeBs:
                - name: "gnb1"
                  tac: 1
                - name: "gnb2"
                  tac: 2
                plmn:
                  mcc: "001"
                  mnc: "01"
                site-name: "enterprise"
                upf:
                  upf-name: "upf"  # associated UPF for this slice. One UPF per Slice.
                  upf-port: 8805

# Override values for omec-user-plane Helm Chart
# https://github.com/omec-project/sdcore-helm-charts/blob/main/bess-upf/values.yaml
omec-user-plane:
  enable: true
  nodeSelectors:
    enabled: true
  resources:
    enabled: false
  images:
    repository: ""    # defaults to Docker Hub
    # following two lines pull busybox from Docker Hub instead of Aether Registry
    tags:
      tools: omecproject/busybox:stable
    # uncomment following section to add update bess image tag
    #tags:
    #  bess: <bess image tag>
    #  pfcpiface: <pfcp image tag>
  config:
    upf:
      name: "oaisim"
      sriov:
        enabled: false    # SRIOV is disabled by default
      hugepage:
        enabled: false    # Should be enabled if DPDK is enabled
      routes:
        - to: {{ ansible_default_ipv4.address }}
          via: 169.254.1.1
      enb:
        subnet: {{ ran_subnet }} # Subnet for the gNB network
      access:
        ipam: static
        cniPlugin: macvlan  # Can be any other plugin. Dictates how IP address are assigned
        iface: {{ core.data_iface }}
        gateway: 192.168.252.1
        ip: 192.168.252.3/24
      core:
        ipam: static
        cniPlugin: macvlan  # Can be any other plugin. Dictates how IP address are assigned
        iface: {{ core.data_iface }}
        gateway: 192.168.250.1
        ip: 192.168.250.3/24
      cfgFiles:
        upf.jsonc:
          mode: af_packet                # This mode implies no DPDK
          hwcksum: true
          log_level: "trace"
          measure_upf: true
          measure_flow: true
          gtppsc: true                   # Extension header enabled in 5G.
          cpiface:
            dnn: "internet"              # Must match Slice dnn
            hostname: "upf"
            #http_port: "8080"
            enable_ue_ip_alloc: false    # If true, UPF allocates address from following pool
            ue_ip_pool: "172.250.0.0/16" # IP pool used UEs if enable_ue_ip_alloc=true
          slice_rate_limit_config:       # Slice-level rate limiting (also controlled by ROC)
            # Uplink
            n6_bps: 10000000000          # 10Gbps
            n6_burst_bytes: 12500000     # 10ms * 10Gbps
            # Downlink
            n3_bps: 10000000000          # 10Gbps
            n3_burst_bytes: 12500000     # 10ms * 10Gbps
